version: "3"
services:
  angular:
    build: ../Frontend/Shortster
    ports:
      - "4200:4200"

  app:
    node: node.js
    image: ./
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
